### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk.github.io#14]
The boxes on the Get involved section are borked - supposed to look more like this: https://web.archive.org/web/20170712153520/https://cdk.github.io/

I do use npm/webpack a fair bit for JS compilation but tend to avoid bootstrap and do my own static layouts to avoid such headaches. 

Do you know what the issue is here @xperrylinn?

**Comment by xperrylinn** [comment]
I'll take a look 👀

**Comment by johnmay** [comment]
Fixed
