### ISSUE TITLE
website does not build

### ISSUE THREAD

**Issue by egonw** [cdk/cdk.github.io#5]
I just tried to compile the website with the command given in the readme:

```shell
npm install
```

But that fails to complete with compile errors... the lasts bits suggest a problem with the node-sass modules, and besides a ton of warnings and notes, this is the error I find it reporting:

```
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/egonw/.node-gyp/10.8.0/include/node -I/home/egonw/.node-gyp/10.8.0/src -I/home/egonw/.node-gyp/10.8.0/deps/uv/include -I/home/egonw/.node-gyp/10.8.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../../nan/nan.h:192,
                 from ../src/binding.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```

**Comment by egonw** [comment]
Versions:

```shell
$ nodejs -v
v10.8.0
$ npm -v
6.2.0
```

**Comment by egonw** [comment]
OK, I now spend two hours trying to figure out how to get this working, but it seems impossible...

We must have CI for this too, and properly maintain it with updates of dependencies :( See https://github.com/cdk/cdk.github.io/issues/6

I'm giving up for now...

**Comment by CS76** [comment]
Make sure you are on the 'source' branch and then install the javascript dependencies/packages using

`> npm install `

Build

`> npm run production`

**Comment by egonw** [comment]
The above is with the `source` branch...

**Comment by CS76** [comment]
I am using node v8.11.3 LTS, npm v5.6.0 and build seems to be working fine.

Are you using `$ npm install` or `$ node install` ??

**Comment by johnmay** [comment]
It's *"npm install"* not "*node install"*.

**Comment by johnmay** [comment]
Hmm I also see it fail Venkata, looks like a problem with SASS

**Comment by egonw** [comment]
Typo, using `npm install`...

**Comment by johnmay** [comment]
Should be fixed, will deploy now but please test.

**Comment by johnmay** [comment]
Wait stil broken in webpack now. Wellcome to NPM :-), it's hell.

**Comment by johnmay** [comment]
Hopefully fixed now, lots of changes with webpack v3 -> v4 so left it at webpack v3.

**Comment by egonw** [comment]
Works for me too! Thanks.
