### ISSUE TITLE
website has security vulnerabilities

### ISSUE THREAD

**Issue by egonw** [cdk/cdk.github.io#6]
... as reported by GitHub:

![image](https://user-images.githubusercontent.com/26721/43759054-66bf5794-9a1e-11e8-9f06-f687524a792e.png)

which links to https://github.com/cdk/cdk.github.io/network/dependencies

**Comment by egonw** [comment]
@CS76, can you help out? Updating the dependencies?

**Comment by CS76** [comment]
Sure, I will have a look @egonw

**Comment by egonw** [comment]
@CS76, yes, please, see also #5 ... I cannot get the website to "compile"... very frustrating...

**Comment by CS76** [comment]
I cannot see the security vulnerabilities, also GitHub doesn't report this on my fork :(  Can you grant me access to the vulnerability alerts on this repo. Thanks

**Comment by egonw** [comment]
I sent you an invite to become a collaborator... can you see it then?

**Comment by CS76** [comment]
I don't see any security vulnerabilities in the [dependency graph page](https://github.com/cdk/cdk.github.io/network/dependencies)

Can you ??? @egonw

**Comment by egonw** [comment]
And now?

**Comment by egonw** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/26721/43767310-0f0ae3c6-9a35-11e8-9b9b-7e7d92663912.png)

**Comment by CS76** [comment]
I can see them now... Will look into it. Thank you

**Comment by johnmay** [comment]
Down to one.

**Comment by egonw** [comment]
Indeed:

![image](https://user-images.githubusercontent.com/26721/43774589-e395b38c-9a49-11e8-95e4-ceb0dd508cfa.png)

**Comment by johnmay** [comment]
BTW not a great idea to post this as an issue, the reason it's kept secret is to make it harder to search for.

**Comment by egonw** [comment]
Good point and solved.
